// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUclcBifwAX1VyuPuEHAM109fn5DBQMks',
    appId: '1:418351958884:web:100a626c13d29c2cb18871',
    messagingSenderId: '418351958884',
    projectId: 'agendaflutter-d8bc2',
    authDomain: 'agendaflutter-d8bc2.firebaseapp.com',
    storageBucket: 'agendaflutter-d8bc2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7QZBqV_Dlf-V-XvncEYNDE7fXNQEokDk',
    appId: '1:418351958884:android:586b4e6dfb2b2460b18871',
    messagingSenderId: '418351958884',
    projectId: 'agendaflutter-d8bc2',
    storageBucket: 'agendaflutter-d8bc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_l3UlBkKvGg6yggLnokDJjYH9xs4sEBY',
    appId: '1:418351958884:ios:14b4b06cfe5038bdb18871',
    messagingSenderId: '418351958884',
    projectId: 'agendaflutter-d8bc2',
    storageBucket: 'agendaflutter-d8bc2.firebasestorage.app',
    iosBundleId: 'com.example.practica32cordan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_l3UlBkKvGg6yggLnokDJjYH9xs4sEBY',
    appId: '1:418351958884:ios:14b4b06cfe5038bdb18871',
    messagingSenderId: '418351958884',
    projectId: 'agendaflutter-d8bc2',
    storageBucket: 'agendaflutter-d8bc2.firebasestorage.app',
    iosBundleId: 'com.example.practica32cordan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUclcBifwAX1VyuPuEHAM109fn5DBQMks',
    appId: '1:418351958884:web:30e1e03543c11e6fb18871',
    messagingSenderId: '418351958884',
    projectId: 'agendaflutter-d8bc2',
    authDomain: 'agendaflutter-d8bc2.firebaseapp.com',
    storageBucket: 'agendaflutter-d8bc2.firebasestorage.app',
  );
}
